# Generated by Django 2.2.1 on 2019-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
